import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Responsive Starter",
  viewport: 'width=device-width, initial-scale=1, maximum-scale=5',
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-dvh bg-neutral-950 text-neutral-100 antialiased text-base md:text-[16px]">
        <div className="flex min-h-dvh flex-col">
          {children}
        </div>
      </body>
    </html>
  );
}
